apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo I am alive! && sleep 3600']
  initContainers:
  - name: init-secret-sync
    image: busybox:1.28
    command: ['sh', '-c', 'echo starting pretend secret-sync']
  - name: init-db
    image: busybox:1.28
    command: ['sh', '-c', 'echo starting pretend database; service mysql start']
