---
#https://www.linuxsysadmins.com/install-kubernetes-cluster-with-ansible/
- name: "Install Docker"
  hosts: 127.0.0.1
  connection: local

  tasks:
    - name: Installing Prerequisites for Docker
      apt:
        update_cache: yes
        cache_valid_time: 21600 # 6 hours.
        pkg: "{{ packages['docker']['prereq'] }}"
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker
        mode: 0600

    - name: Install Docker Engine.
      apt:
        pkg: "{{ packages['docker']['engine'] }}"
        state: present

    - name: Add user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Enable service docker and enable persistently
      service:
        name: docker
        enabled: yes

