---
- name: Install packages
  hosts: 127.0.0.1
  connection: local

  roles:
    - common

- name: Install Docker
  hosts: 127.0.0.1
  connection: local

  roles:
    - docker

- name: Install Kubernetes
  hosts: 127.0.0.1
  connection: local

  roles:
    - kubernetes

