#!/usr/bin/env node
// gcd(33,27)

if (process.argv.length < 4) {
    console.log(`Usage: ${process.argv[1]} [a] [b]`);
    return;
}

const gcd = (a, b) => {
//    console.log(a, b);
    if (a % b === 0) {
        return b;
    }

    return gcd(b, a % b);
};

console.log(
    gcd(
        process.argv[2] * 1,
        process.argv[3] * 1
    )
);

