# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.box_version = "1.9.28"
  config.vm.box_url = "https://app.vagrantup.com/generic/boxes/debian9"

  config.vm.network :forwarded_port, guest: 80, host: 4444

  config.vm.synced_folder ".", "/vagrant"

  config.vm.provision "ansible_local" do |ansible|
    ansible.groups = {
      "webservers" => ["default"]
    }

    ansible.install = true
    ansible.install_mode = "default"

    ansible.playbook = "playbook.yml"

    ansible.version = "latest"
  end
end

