# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "generic/debian9"
NODE_COUNT = 3

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "lb1" do |lb1|
    lb1.vm.box = BOX_IMAGE
    lb1.vm.hostname = "lb1"
    lb1.vm.network :private_network, ip: "10.0.0.10"
    lb1.vm.network :forwarded_port, host: 4444, guest: 80
  end

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provision :ansible do |ansible|
    ansible.groups = {
      "lb" => ["lb1"],
      "webservers" => ["node1", "node2", "node3"]
    }

#    ansible.install = true
#    ansible.install_mode = "default"

    # Disable default limit to connect to all the machines
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    ansible.version = "latest"
  end
end

