# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.box_version = "8.11.1"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/jessie64"

  config.vm.network :forwarded_port, guest: 80, host: 4444

  config.vm.provision "ansible" do |ansible|
    ansible.groups = {
      "webservers" => ["default"]
    }
    ansible.playbook = "playbook.yml"
  end
end

