# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_IMAGE = "generic/debian9"
NODE_COUNT = 1

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  (1..NODE_COUNT).each do |i|
    config.vm.define "chomsky#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "chomsky#{i}"
      subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
    end
  end

  config.vm.provision :ansible do |ansible|
#    ansible.install = true
#    ansible.install_mode = "default"

    # Disable default limit to connect to all the machines
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    ansible.version = "latest"
  end
end

