BOX_IMAGE = "ubuntu/bionic64"
MASTERS = 1
WORKERS = 3
POD_CIDR = "172.18.0.0/16"
API_ADV_ADDRESS = "10.8.8.10"
MSG = "benjamintoll.com"
COMMON_SCRIPT_URL = "/vagrant/scripts/common.sh"
MASTER_SCRIPT_URL = "/vagrant/scripts/master.sh"
WORKER_SCRIPT_URL = "/vagrant/scripts/worker.sh"
CPU = 4
MEMORY = 12288

Vagrant.configure("2") do |config|
    config.vm.provision "shell" do |s|
        s.inline = <<-SCRIPT
            mkdir -p $HOME/.config/.bt
            cp -p #{COMMON_SCRIPT_URL} $HOME/.config/.bt/common.sh
            $HOME/.config/.bt/common.sh #{MSG}
        SCRIPT
    end

    (0..MASTERS-1).each do |i|
        config.vm.define "bt-master-#{i}" do |subconfig|
            subconfig.vm.box = BOX_IMAGE
            subconfig.vm.hostname = "bt-master-#{i}"
            subconfig.vm.network :private_network, ip: "10.8.8.#{i + 10}"
            subconfig.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--cpus", CPU]
                vb.memory = MEMORY
            end

            subconfig.vm.provision "shell" do |s|
                s.inline = <<-SCRIPT
                    mkdir -p $HOME/.config/.bt
                    cp -p #{MASTER_SCRIPT_URL} $HOME/.config/.bt/master.sh
                    $HOME/.config/.bt/master.sh #{MSG} #{i} #{POD_CIDR} #{API_ADV_ADDRESS}
                SCRIPT
            end
        end
    end

    (0..WORKERS-1).each do |i|
        config.vm.define "bt-worker-#{i}" do |subconfig|
            subconfig.vm.box = BOX_IMAGE
            subconfig.vm.hostname = "bt-worker-#{i}"
            subconfig.vm.network :private_network, ip: "10.8.8.#{i + 20}"
            subconfig.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--cpus", CPU]
                vb.memory = MEMORY
            end

            subconfig.vm.provision "shell" do |s|
                s.inline = <<-SCRIPT
                    mkdir -p $HOME/.config/.bt
                    cp -p #{WORKER_SCRIPT_URL} $HOME/.config/.bt/worker.sh
                    $HOME/.config/.bt/worker.sh #{MSG} #{i} #{POD_CIDR} #{API_ADV_ADDRESS}
                SCRIPT
            end
        end
    end

    config.vm.provision "shell",
    run: "always",
    inline: "swapoff -a"
end

