---
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 36000

- name: Install base packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - bc
    - build-essential
    - curl
    - gdb
    - git
    - sudo
    - vim

- name: Add the greatest hero of them all
  user:
    name: btoll
    password: '$6$iTCFyYyW$8EZV5/rnqXqUm/YUfJUklrECqOOirR/D0iTJGLRwRnxMzhNA3PYwLO3RFpXXXFGp2Wnv8OGzXrUZ94c0NyKI9/'
    groups:
      - root
      - sudo
    state: present
    shell: /bin/bash

