# -*- mode: ruby -*-
# vi: set ft=ruby :

#BOX_IMAGE = "hashicorp/precise64"
BOX_IMAGE = "centos/7"
NIC = "wlp3s0"
PROVIDER = "virtualbox"
MASTERS = 1
WORKERS = 0

Vagrant.configure("2") do |config|
    config.vm.define "testes" do |subconfig|
        subconfig.vm.box = BOX_IMAGE
        subconfig.vm.hostname = "testes"
        subconfig.vm.network :public_network, ip: "192.168.1.100", bridge: NIC

        subconfig.vm.provider PROVIDER do |v|
            v.name = "testes"
        end
    end

    config.vm.provision "ansible_local" do |ansible|
        ansible.compatibility_mode = "2.0"
        ansible.playbook = "playbook.yml"
        ansible.install_mode = "default"
    end
end

