---
- name: Update repositories cache
  apt:
    update_cache: yes
    cache_valid_time: 36000

- name: Install packages
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - nginx
    - python-pip
    - sudo

