# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "private_network", ip: "192.168.33.10"

    config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y openjdk-11-jdk
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | apt-key add -
        echo "deb http://pkg.jenkins-ci.org/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
        apt-get update
        apt-get install -y jenkins
#        cp /var/lib/jenkins/secrets/initialAdminPassword /vagrant
        # 192.168.33.10:8080/login
    SHELL
end

